name: bPotionPvP
author: BasicNetworkDev
version: 1.0
depend: [ProtocolLib]
main: me.giantcrack.bpvp.Main
commands:
   spawn:
   setspawn:
   team:
   duel:
   setedit:
   leave:
   arena:
   accept:
   spectate:
   pvp:
   di:
   stats:
   set:
permissions:
   blocks.break:
      default: false
      description: Perm for the staff